// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace Resolvers
{
    public class ConfigDataResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new ConfigDataResolver();

        private ConfigDataResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = ConfigDataResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class ConfigDataResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static ConfigDataResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(11)
            {
                { typeof(global::System.Collections.Generic.List<int>), 0 },
                { typeof(global::System.Collections.Generic.List<long>), 1 },
                { typeof(global::System.Collections.Generic.List<string>), 2 },
                { typeof(global::Geek.Client.Config.t_itemBeanDeserializeProxy), 3 },
                { typeof(global::Geek.Client.Config.t_itemBeanDeserializeProxyData), 4 },
                { typeof(global::Geek.Client.Config.t_languageBeanDeserializeProxy), 5 },
                { typeof(global::Geek.Client.Config.t_languageBeanDeserializeProxyData), 6 },
                { typeof(global::Geek.Client.Config.t_test2BeanDeserializeProxy), 7 },
                { typeof(global::Geek.Client.Config.t_test2BeanDeserializeProxyData), 8 },
                { typeof(global::Geek.Client.Config.t_testBeanDeserializeProxy), 9 },
                { typeof(global::Geek.Client.Config.t_testBeanDeserializeProxyData), 10 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ListFormatter<int>();
                case 1: return new global::MessagePack.Formatters.ListFormatter<long>();
                case 2: return new global::MessagePack.Formatters.ListFormatter<string>();
                case 3: return new Formatters.Geek.Client.Config.t_itemBeanDeserializeProxyFormatter();
                case 4: return new Formatters.Geek.Client.Config.t_itemBeanDeserializeProxyDataFormatter();
                case 5: return new Formatters.Geek.Client.Config.t_languageBeanDeserializeProxyFormatter();
                case 6: return new Formatters.Geek.Client.Config.t_languageBeanDeserializeProxyDataFormatter();
                case 7: return new Formatters.Geek.Client.Config.t_test2BeanDeserializeProxyFormatter();
                case 8: return new Formatters.Geek.Client.Config.t_test2BeanDeserializeProxyDataFormatter();
                case 9: return new Formatters.Geek.Client.Config.t_testBeanDeserializeProxyFormatter();
                case 10: return new Formatters.Geek.Client.Config.t_testBeanDeserializeProxyDataFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
