//// <auto-generated>
//// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
//// </auto-generated>

//#pragma warning disable 618
//#pragma warning disable 612
//#pragma warning disable 414
//#pragma warning disable 168
//#pragma warning disable CS1591 // document public APIs

//#pragma warning disable SA1129 // Do not use default value type constructor
//#pragma warning disable SA1309 // Field names should not begin with underscore
//#pragma warning disable SA1312 // Variable names should begin with lower-case letter
//#pragma warning disable SA1403 // File may only contain a single namespace
//#pragma warning disable SA1649 // File name should match first type name

//namespace Geek.Server
//{

//    public class SerializableFormatter : 
//        global::MessagePack.Formatters.IMessagePackFormatter<global::Geek.Server.Serializable>
//    {

//        public virtual void Serialize(
//            ref global::MessagePack.MessagePackWriter writer, 
//            global::Geek.Server.Serializable value, 
//            global::MessagePack.MessagePackSerializerOptions options)
//        {
//        }


//        public global::Geek.Server.Serializable Deserialize(
//            ref global::MessagePack.MessagePackReader reader, 
//            global::MessagePack.MessagePackSerializerOptions options,
//            global::Geek.Server.Serializable target)
//        {
//            return target;
//        }


//        public virtual global::Geek.Server.Serializable Deserialize(
//            ref global::MessagePack.MessagePackReader reader, 
//            global::MessagePack.MessagePackSerializerOptions options)
//        {
//            return null;
//        }
//    }
//}

//#pragma warning restore 168
//#pragma warning restore 414
//#pragma warning restore 618
//#pragma warning restore 612

//#pragma warning restore SA1129 // Do not use default value type constructor
//#pragma warning restore SA1309 // Field names should not begin with underscore
//#pragma warning restore SA1312 // Variable names should begin with lower-case letter
//#pragma warning restore SA1403 // File may only contain a single namespace
//#pragma warning restore SA1649 // File name should match first type name
